# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settlement.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1017, 673)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 701, 618))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignRight)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignRight)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignRight)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignRight)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5, 0, QtCore.Qt.AlignRight)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6, 0, QtCore.Qt.AlignRight)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7, 0, QtCore.Qt.AlignRight)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8, 0, QtCore.Qt.AlignRight)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10, 0, QtCore.Qt.AlignRight)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11, 0, QtCore.Qt.AlignRight)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12, 0, QtCore.Qt.AlignRight)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13, 0, QtCore.Qt.AlignRight)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14, 0, QtCore.Qt.AlignRight)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15, 0, QtCore.Qt.AlignRight)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16, 0, QtCore.Qt.AlignRight)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit.setMaximumSize(QtCore.QSize(579, 62))
        self.textEdit.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.textEdit_2 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_2.setMaximumSize(QtCore.QSize(579, 62))
        self.textEdit_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_2.addWidget(self.textEdit_2)
        self.textEdit_3 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_3.setMaximumSize(QtCore.QSize(579, 62))
        self.textEdit_3.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_2.addWidget(self.textEdit_3)
        self.textEdit_4 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_4.setMaximumSize(QtCore.QSize(579, 62))
        self.textEdit_4.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout_2.addWidget(self.textEdit_4)
        self.textEdit_5 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_5.setMaximumSize(QtCore.QSize(579, 62))
        self.textEdit_5.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.textEdit_5.setObjectName("textEdit_5")
        self.verticalLayout_2.addWidget(self.textEdit_5)
        self.textEdit_6 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_6.setMaximumSize(QtCore.QSize(579, 62))
        self.textEdit_6.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.textEdit_6.setObjectName("textEdit_6")
        self.verticalLayout_2.addWidget(self.textEdit_6)
        self.textEdit_7 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_7.setMaximumSize(QtCore.QSize(579, 62))
        self.textEdit_7.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.textEdit_7.setObjectName("textEdit_7")
        self.verticalLayout_2.addWidget(self.textEdit_7)
        self.textEdit_8 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_8.setMaximumSize(QtCore.QSize(579, 62))
        self.textEdit_8.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.textEdit_8.setObjectName("textEdit_8")
        self.verticalLayout_2.addWidget(self.textEdit_8)
        self.textEdit_9 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_9.setMaximumSize(QtCore.QSize(579, 62))
        self.textEdit_9.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.textEdit_9.setObjectName("textEdit_9")
        self.verticalLayout_2.addWidget(self.textEdit_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(790, 380, 181, 65))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.spinBox.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_4.addWidget(self.spinBox)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(790, 510, 181, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(790, 250, 181, 71))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)
        self.textEdit_10 = QtWidgets.QTextEdit(self.verticalLayoutWidget_5)
        self.textEdit_10.setMaximumSize(QtCore.QSize(179, 34))
        self.textEdit_10.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.textEdit_10.setObjectName("textEdit_10")
        self.verticalLayout_5.addWidget(self.textEdit_10)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.textEdit, self.textEdit_3)
        Dialog.setTabOrder(self.textEdit_3, self.textEdit_4)
        Dialog.setTabOrder(self.textEdit_4, self.textEdit_5)
        Dialog.setTabOrder(self.textEdit_5, self.textEdit_6)
        Dialog.setTabOrder(self.textEdit_6, self.textEdit_7)
        Dialog.setTabOrder(self.textEdit_7, self.textEdit_8)
        Dialog.setTabOrder(self.textEdit_8, self.textEdit_9)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Total Settlement</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Attorney Fees </span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Investigator Fees</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Deposition Fees</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Mediation Fees</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Medical Records</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Efiling</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Citation Services</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Other</span></p></body></html>"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">$</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Dialog", "%"))
        self.comboBox.setItemText(1, _translate("Dialog", "$"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">$</span></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">$</span></p></body></html>"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">$</span></p></body></html>"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">$</span></p></body></html>"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">$</span></p></body></html>"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">$</span></p></body></html>"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">$</span></p></body></html>"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Number of Providers</span></p></body></html>"))
        self.pushButton.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Continue</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Continue"))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Client\'s Name</span></p></body></html>"))
        self.textEdit_10.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
